version : '3'

services:
    elb:
        labels:
          kompose.service.expose: true
        image: docker.io/haproxytech/kubernetes-ingress
        ports:
            - "8100:8100"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    goapp1:
        image: goapp
        ports:
          - 8081
        environment:
            - APPPORT=8081
    goapp2:
        image: goapp
        ports:
          - 8082
        environment:
            - APPPORT=8082
    goapp3:
        image: goapp
        ports:
          - 8083
        environment:
            - APPPORT=8083
